M48
; DRILL file {KiCad 7.0.6} date Fri Jan  5 11:00:15 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-05T11:00:15+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
%
G90
G05
T1
X2.5866Y-2.2598
X2.5866Y-2.3583
X2.7835Y-2.063
X2.9803Y-2.2598
X2.9803Y-2.3583
T0
M30
